### ISSUE TITLE
test prob

### ISSUE THREAD

**Issue by rickdog** [cujojs/rest#115]
wazzup?:
```
rickdog@RICKDOG-DELL /C/Users/rickdog/when/when/node_modules/rest (master)
$ npm install
npm WARN package.json poly@0.5.1 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json wire@0.9.4 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json curl@0.7.3 'repositories' (plural) Not supported. Please pick one as the 'repository' field

rickdog@RICKDOG-DELL /C/Users/rickdog/when/when/node_modules/rest (master)
$ npm test

> rest@1.3.1 test c:\Users\rickdog\when\when\node_modules\rest
> npm run-script lint && npm run-script buster


> rest@1.3.1 lint c:\Users\rickdog\when\when\node_modules\rest
> jshint .

events.js:73
      throw er; // Unhandled 'error' event
            ^
Error: spawn c:\Users\rickdog\when\when\node_modules\rest\node_modules\test-support\node_modules\.bin\proxyCmd ENOENT
    at exports._errnoException (util.js:732:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1017:32)
    at child_process.js:1108:20
    at process._tickCallback (node.js:337:11)
    at Function.Module.runMain (module.js:489:11)
    at startup (node.js:111:16)
    at node.js:809:3

npm ERR! Windows_NT 6.0.6001
npm ERR! argv "c:\\Program Files\\iojs\\\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "lint"
npm ERR! node v1.0.1
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE
npm ERR! rest@1.3.1 lint: `jshint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rest@1.3.1 lint script 'jshint .'.
npm ERR! This is most likely a problem with the rest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jshint .
npm ERR! You can get their info via:
npm ERR!     npm owner ls rest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\rickdog\when\when\node_modules\rest\npm-debug.log
npm ERR! Test failed.  See above for more details.
```
```
rickdog@RICKDOG-DELL /C/Users/rickdog/when/when/node_modules/rest (master)
$ ls c:/Users/rickdog/when/when/node_modules/rest/node_modules/test-support/node_modules/.bin/
buster           buster-autotest.cmd  buster-server.cmd  buster-static.cmd  buster-test.cmd  jshint      json5      wd
buster-autotest  buster-server        buster-static      buster-test        buster.cmd       jshint.cmd  json5.cmd  wd.cmd
```

**Comment by scothis** [comment]
Io.js has issues with buster, our test runner. rest.js is known to work with io.js. You can take a look at the dev20 branch to see it running on io.js via mocha
