### ISSUE TITLE
 buster test --node fails to run

### ISSUE THREAD

**Issue by bodell** [cujojs/rest#156]
I am getting an error when running `npm test`

Here is the output:

```
E:\Projects\github\rest-js>npm test

> rest@2.0.1-pre test E:\Projects\github\rest-js
> npm run-script lint && npm run-script buster


> rest@2.0.1-pre lint E:\Projects\github\rest-js
> eslint .


> rest@2.0.1-pre buster E:\Projects\github\rest-js
> buster test --node

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn E:\Projects\github\rest-js\node_modules\test-support\node_modules\.bin\proxyCmd ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bodell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "buster"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! rest@2.0.1-pre buster: `buster test --node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rest@2.0.1-pre buster script 'buster test --node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     buster test --node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projects\github\rest-js\npm-debug.log
npm ERR! Test failed.  See above for more details.
```

Any help would be greatly appreciated. Thanks!

**Comment by scothis** [comment]
rest.js is no longer maintained
