### ISSUE TITLE
ReferenceError: location is not defined when running application

### ISSUE THREAD

**Issue by shesko** [cujojs/rest#166]
Hello,
Whenever I run the following command:

```NODE_ENV=production node_modules/.bin/babel-node --presets 'react,es2015' src/server.js```

I get this error:

```
/Users/ShEsKo/Documents/Work/app/node_modules/rest/UrlBuilder.js:215
console.log("location.href", location.href);
                             ^

ReferenceError: location is not defined
    at Object.<anonymous> (/Users/ShEsKo/Documents/Work/app/node_modules/rest/UrlBuilder.js:215:30)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ShEsKo/Documents/Work/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ShEsKo/Documents/Work/app/node_modules/rest/interceptor/pathPrefix.js:13:14)

```

Any idea what I can do to stop it? I literally have no idea what to do. :/

**Comment by scothis** [comment]
rest.js is no longer maintained
